[package]
name = "sentiric-proxy-service"
version = "1.2.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.11", features = ["tls", "tls-roots"] }
prost = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
dotenvy = "0.15"
anyhow = "1.0"
thiserror = "1.0"
hyper = { version = "0.14.28", features = ["full"] } 
config = "0.14" 
uuid = { version = "1.8", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] } # EKLE

redis = { version = "0.26", features = ["tokio-rustls-comp"] }

sentiric-sip-core = { git = "https://github.com/sentiric/sentiric-sip-core.git", tag = "v1.3.3" }
sentiric-contracts = { git = "https://github.com/sentiric/sentiric-contracts.git", tag = "v1.13.6" }
rand = "0.9.2"
